name: Build

on:
  push:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: ubuntu-latest
          name: linux-x64
        - os: macos-latest
          name: macos-x64
        - os: windows-latest
          name: windows-x64
    steps:
    - name: Check Home
      shell: bash
      run: find $HOME/.ssh || echo "$HOME/.ssh not exit"

    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Check PWD
      run: pwd

    - name: Check CMake
      working-directory: ${{github.workspace}}/build
      run: cmake --version

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_VEROBSE_MAKEFILE=ON ..

    - name: Build
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE --target package

    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: ctest -C $BUILD_TYPE --output-on-failure

    - name: Setup SSH
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      shell: bash
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.DEPLOY_SSH_KEY }}"

    - name: Upload
      run: |
        if [ "${{runner.os}}" = "Windows" ]; then
          rsync -av -e "ssh -p $SSH_INIT_PORT $SSH_INIT_ARGS" build/hello-*.tar.gz $SSH_FILE_DEST
        else
          scp -P $SSH_INIT_PORT $SSH_INIT_ARGS build/hello-*.tar.gz $SSH_FILE_DEST
        fi
      shell: bash
      env:
        SSH_INIT_PORT: 10022
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        SSH_INIT_ARGS: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
        SSH_FILE_DEST: deploy@${{secrets.DEPLOY_SSH_HOST}}:${{secrets.DEPLOY_SSH_PATH}}/var/www/archives/FixCommA/hello-${{matrix.name}}.tar.gz
